package com.computer.subscribe.pojo;

import java.util.Date;

public class TSubscribe {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_subscribe.id
     *
     * @mbggenerated Sun Apr 11 11:21:42 CST 2021
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_subscribe.applicant
     *
     * @mbggenerated Sun Apr 11 11:21:42 CST 2021
     */
    private Long applicant;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_subscribe.reviewer
     *
     * @mbggenerated Sun Apr 11 11:21:42 CST 2021
     */
    private Long reviewer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_subscribe.subscribe_status
     *
     * @mbggenerated Sun Apr 11 11:21:42 CST 2021
     */
    private Integer subscribeStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_subscribe.room_num
     *
     * @mbggenerated Sun Apr 11 11:21:42 CST 2021
     */
    private Integer roomNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_subscribe.application_start_time
     *
     * @mbggenerated Sun Apr 11 11:21:42 CST 2021
     */
    private Date applicationStartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_subscribe.use_interval
     *
     * @mbggenerated Sun Apr 11 11:21:42 CST 2021
     */
    private Integer useInterval;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_subscribe.handle_time
     *
     * @mbggenerated Sun Apr 11 11:21:42 CST 2021
     */
    private Date handleTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_subscribe.id
     *
     * @return the value of t_subscribe.id
     *
     * @mbggenerated Sun Apr 11 11:21:42 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_subscribe.id
     *
     * @param id the value for t_subscribe.id
     *
     * @mbggenerated Sun Apr 11 11:21:42 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_subscribe.applicant
     *
     * @return the value of t_subscribe.applicant
     *
     * @mbggenerated Sun Apr 11 11:21:42 CST 2021
     */
    public Long getApplicant() {
        return applicant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_subscribe.applicant
     *
     * @param applicant the value for t_subscribe.applicant
     *
     * @mbggenerated Sun Apr 11 11:21:42 CST 2021
     */
    public void setApplicant(Long applicant) {
        this.applicant = applicant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_subscribe.reviewer
     *
     * @return the value of t_subscribe.reviewer
     *
     * @mbggenerated Sun Apr 11 11:21:42 CST 2021
     */
    public Long getReviewer() {
        return reviewer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_subscribe.reviewer
     *
     * @param reviewer the value for t_subscribe.reviewer
     *
     * @mbggenerated Sun Apr 11 11:21:42 CST 2021
     */
    public void setReviewer(Long reviewer) {
        this.reviewer = reviewer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_subscribe.subscribe_status
     *
     * @return the value of t_subscribe.subscribe_status
     *
     * @mbggenerated Sun Apr 11 11:21:42 CST 2021
     */
    public Integer getSubscribeStatus() {
        return subscribeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_subscribe.subscribe_status
     *
     * @param subscribeStatus the value for t_subscribe.subscribe_status
     *
     * @mbggenerated Sun Apr 11 11:21:42 CST 2021
     */
    public void setSubscribeStatus(Integer subscribeStatus) {
        this.subscribeStatus = subscribeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_subscribe.room_num
     *
     * @return the value of t_subscribe.room_num
     *
     * @mbggenerated Sun Apr 11 11:21:42 CST 2021
     */
    public Integer getRoomNum() {
        return roomNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_subscribe.room_num
     *
     * @param roomNum the value for t_subscribe.room_num
     *
     * @mbggenerated Sun Apr 11 11:21:42 CST 2021
     */
    public void setRoomNum(Integer roomNum) {
        this.roomNum = roomNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_subscribe.application_start_time
     *
     * @return the value of t_subscribe.application_start_time
     *
     * @mbggenerated Sun Apr 11 11:21:42 CST 2021
     */
    public Date getApplicationStartTime() {
        return applicationStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_subscribe.application_start_time
     *
     * @param applicationStartTime the value for t_subscribe.application_start_time
     *
     * @mbggenerated Sun Apr 11 11:21:42 CST 2021
     */
    public void setApplicationStartTime(Date applicationStartTime) {
        this.applicationStartTime = applicationStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_subscribe.use_interval
     *
     * @return the value of t_subscribe.use_interval
     *
     * @mbggenerated Sun Apr 11 11:21:42 CST 2021
     */
    public Integer getUseInterval() {
        return useInterval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_subscribe.use_interval
     *
     * @param useInterval the value for t_subscribe.use_interval
     *
     * @mbggenerated Sun Apr 11 11:21:42 CST 2021
     */
    public void setUseInterval(Integer useInterval) {
        this.useInterval = useInterval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_subscribe.handle_time
     *
     * @return the value of t_subscribe.handle_time
     *
     * @mbggenerated Sun Apr 11 11:21:42 CST 2021
     */
    public Date getHandleTime() {
        return handleTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_subscribe.handle_time
     *
     * @param handleTime the value for t_subscribe.handle_time
     *
     * @mbggenerated Sun Apr 11 11:21:42 CST 2021
     */
    public void setHandleTime(Date handleTime) {
        this.handleTime = handleTime;
    }
}