package com.computer.subscribe.pojo;

import java.util.Date;

import javax.validation.constraints.Future;
import javax.validation.constraints.Max;
import javax.validation.constraints.Min;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Null;

import org.hibernate.validator.constraints.Range;

import lombok.ToString;

@ToString
public class TSubscribe {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column t_subscribe.id
	 *
	 * @mbggenerated Sun Apr 11 13:28:41 CST 2021
	 */
	private Long id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column t_subscribe.applicant
	 *
	 * @mbggenerated Sun Apr 11 13:28:41 CST 2021
	 */
	@NotNull(message = "申请者不能为空")
	private Long applicant;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column t_subscribe.reviewer
	 *
	 * @mbggenerated Sun Apr 11 11:21:42 CST 2021
	 */
	@Null
	private Long reviewer;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column t_subscribe.subscribe_status
	 *
	 * @mbggenerated Sun Apr 11 11:21:42 CST 2021
	 */
	@Range(min = 0, max = 4)
	private Integer subscribeStatus;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column t_subscribe.room_num
	 *
	 * @mbggenerated Sun Apr 11 11:21:42 CST 2021
	 */
	@NotNull(message = "机房编号不能为空")
	@Min(value = 0, message = "机房编号不得小于 0")
	@Max(value = 1000, message = "机房编号不得大于 1000")
	private Integer roomNum;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column t_subscribe.application_start_time
	 *
	 * @mbggenerated Sun Apr 11 11:21:42 CST 2021
	 */
	private Date applicationStartTime;

	/**
	 * 申请时用时间段,分为上午,下午,夜晚
	 * 
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column t_subscribe.use_interval
	 *
	 * @mbggenerated Sun Apr 11 11:21:42 CST 2021
	 */
	@NotNull(message = "申请使用时段(上午,下午,夜晚)不能为空")
	@Min(value = 0, message = "使用时段不得早于上午")
	@Max(value = 2, message = "使用时段不得晚于夜晚")
	private Integer useInterval;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column t_subscribe.handle_time
	 *
	 * @mbggenerated Sun Apr 11 13:28:41 CST 2021
	 */
	@Null
	private Date handleTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column t_subscribe.apply_use_date
	 *
	 * @mbggenerated Sun Apr 11 13:28:41 CST 2021
	 */
	@NotNull(message = "申请使用机房的具体日期,不能为空")
	@Future(message = "申请使用机房的具体日期必须比当前晚")
	private Date applyUseDate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column t_subscribe.id
	 *
	 * @return the value of t_subscribe.id
	 *
	 * @mbggenerated Sun Apr 11 13:28:41 CST 2021
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column t_subscribe.id
	 *
	 * @param id the value for t_subscribe.id
	 *
	 * @mbggenerated Sun Apr 11 13:28:41 CST 2021
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column t_subscribe.applicant
	 *
	 * @return the value of t_subscribe.applicant
	 *
	 * @mbggenerated Sun Apr 11 13:28:41 CST 2021
	 */
	public Long getApplicant() {
		return applicant;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column t_subscribe.applicant
	 *
	 * @param applicant the value for t_subscribe.applicant
	 *
	 * @mbggenerated Sun Apr 11 13:28:41 CST 2021
	 */
	public void setApplicant(Long applicant) {
		this.applicant = applicant;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column t_subscribe.reviewer
	 *
	 * @return the value of t_subscribe.reviewer
	 *
	 * @mbggenerated Sun Apr 11 13:28:41 CST 2021
	 */
	public Long getReviewer() {
		return reviewer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column t_subscribe.reviewer
	 *
	 * @param reviewer the value for t_subscribe.reviewer
	 *
	 * @mbggenerated Sun Apr 11 13:28:41 CST 2021
	 */
	public void setReviewer(Long reviewer) {
		this.reviewer = reviewer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column t_subscribe.subscribe_status
	 *
	 * @return the value of t_subscribe.subscribe_status
	 *
	 * @mbggenerated Sun Apr 11 13:28:41 CST 2021
	 */
	public Integer getSubscribeStatus() {
		return subscribeStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column t_subscribe.subscribe_status
	 *
	 * @param subscribeStatus the value for t_subscribe.subscribe_status
	 *
	 * @mbggenerated Sun Apr 11 13:28:41 CST 2021
	 */
	public void setSubscribeStatus(Integer subscribeStatus) {
		this.subscribeStatus = subscribeStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column t_subscribe.room_num
	 *
	 * @return the value of t_subscribe.room_num
	 *
	 * @mbggenerated Sun Apr 11 13:28:41 CST 2021
	 */
	public Integer getRoomNum() {
		return roomNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column t_subscribe.room_num
	 *
	 * @param roomNum the value for t_subscribe.room_num
	 *
	 * @mbggenerated Sun Apr 11 13:28:41 CST 2021
	 */
	public void setRoomNum(Integer roomNum) {
		this.roomNum = roomNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column t_subscribe.application_start_time
	 *
	 * @return the value of t_subscribe.application_start_time
	 *
	 * @mbggenerated Sun Apr 11 13:28:41 CST 2021
	 */
	public Date getApplicationStartTime() {
		return applicationStartTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column t_subscribe.application_start_time
	 *
	 * @param applicationStartTime the value for t_subscribe.application_start_time
	 *
	 * @mbggenerated Sun Apr 11 13:28:41 CST 2021
	 */
	public void setApplicationStartTime(Date applicationStartTime) {
		this.applicationStartTime = applicationStartTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column t_subscribe.use_interval
	 *
	 * @return the value of t_subscribe.use_interval
	 *
	 * @mbggenerated Sun Apr 11 13:28:41 CST 2021
	 */
	public Integer getUseInterval() {
		return useInterval;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column t_subscribe.use_interval
	 *
	 * @param useInterval the value for t_subscribe.use_interval
	 *
	 * @mbggenerated Sun Apr 11 13:28:41 CST 2021
	 */
	public void setUseInterval(Integer useInterval) {
		this.useInterval = useInterval;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column t_subscribe.handle_time
	 *
	 * @return the value of t_subscribe.handle_time
	 *
	 * @mbggenerated Sun Apr 11 13:28:41 CST 2021
	 */
	public Date getHandleTime() {
		return handleTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column t_subscribe.handle_time
	 *
	 * @param handleTime the value for t_subscribe.handle_time
	 *
	 * @mbggenerated Sun Apr 11 13:28:41 CST 2021
	 */
	public void setHandleTime(Date handleTime) {
		this.handleTime = handleTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column t_subscribe.apply_use_date
	 *
	 * @return the value of t_subscribe.apply_use_date
	 *
	 * @mbggenerated Sun Apr 11 13:28:41 CST 2021
	 */
	public Date getApplyUseDate() {
		return applyUseDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column t_subscribe.apply_use_date
	 *
	 * @param applyUseDate the value for t_subscribe.apply_use_date
	 *
	 * @mbggenerated Sun Apr 11 13:28:41 CST 2021
	 */
	public void setApplyUseDate(Date applyUseDate) {
		this.applyUseDate = applyUseDate;
	}
}