package com.computer.subscribe.pojo;

public class TUser {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column t_user.id
	 *
	 * @mbggenerated Tue Mar 16 04:16:37 CST 2021
	 */
	private Integer id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column t_user.user_num
	 *
	 * @mbggenerated Tue Mar 16 04:16:37 CST 2021
	 */
	private Integer userNum;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column t_user.user_name
	 *
	 * @mbggenerated Tue Mar 16 04:16:37 CST 2021
	 */
	private String userName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column t_user.phone
	 *
	 * @mbggenerated Tue Mar 16 04:16:37 CST 2021
	 */
	private String phone;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column t_user.mailbox
	 *
	 * @mbggenerated Tue Mar 16 04:16:37 CST 2021
	 */
	private String mailbox;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column t_user.role
	 *
	 * @mbggenerated Tue Mar 16 04:16:37 CST 2021
	 */
	private Integer role;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column t_user.password
	 *
	 * @mbggenerated Tue Mar 16 04:16:37 CST 2021
	 */
	private String password;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column t_user.salt
	 *
	 * @mbggenerated Tue Mar 16 04:16:37 CST 2021
	 */
	private String salt;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column t_user.id
	 *
	 * @return the value of t_user.id
	 *
	 * @mbggenerated Tue Mar 16 04:16:37 CST 2021
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column t_user.id
	 *
	 * @param id the value for t_user.id
	 *
	 * @mbggenerated Tue Mar 16 04:16:37 CST 2021
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column t_user.user_num
	 *
	 * @return the value of t_user.user_num
	 *
	 * @mbggenerated Tue Mar 16 04:16:37 CST 2021
	 */
	public Integer getUserNum() {
		return userNum;
	}

	/**
	 * <b>最多允许九位数字</b><br>
	 * 
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column t_user.user_num
	 *
	 * @param userNum the value for t_user.user_num
	 *
	 * @mbggenerated Tue Mar 16 04:16:37 CST 2021
	 */
	public void setUserNum(Integer userNum) {
		this.userNum = userNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column t_user.user_name
	 *
	 * @return the value of t_user.user_name
	 *
	 * @mbggenerated Tue Mar 16 04:16:37 CST 2021
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column t_user.user_name
	 *
	 * @param userName the value for t_user.user_name
	 *
	 * @mbggenerated Tue Mar 16 04:16:37 CST 2021
	 */
	public void setUserName(String userName) {
		this.userName = userName == null ? null : userName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column t_user.phone
	 *
	 * @return the value of t_user.phone
	 *
	 * @mbggenerated Tue Mar 16 04:16:37 CST 2021
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column t_user.phone
	 *
	 * @param phone the value for t_user.phone
	 *
	 * @mbggenerated Tue Mar 16 04:16:37 CST 2021
	 */
	public void setPhone(String phone) {
		this.phone = phone == null ? null : phone.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column t_user.mailbox
	 *
	 * @return the value of t_user.mailbox
	 *
	 * @mbggenerated Tue Mar 16 04:16:37 CST 2021
	 */
	public String getMailbox() {
		return mailbox;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column t_user.mailbox
	 *
	 * @param mailbox the value for t_user.mailbox
	 *
	 * @mbggenerated Tue Mar 16 04:16:37 CST 2021
	 */
	public void setMailbox(String mailbox) {
		this.mailbox = mailbox == null ? null : mailbox.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column t_user.role
	 *
	 * @return the value of t_user.role
	 *
	 * @mbggenerated Tue Mar 16 04:16:37 CST 2021
	 */
	public Integer getRole() {
		return role;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column t_user.role
	 *
	 * @param role the value for t_user.role
	 *
	 * @mbggenerated Tue Mar 16 04:16:37 CST 2021
	 */
	public void setRole(Integer role) {
		this.role = role;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column t_user.password
	 *
	 * @return the value of t_user.password
	 *
	 * @mbggenerated Tue Mar 16 04:16:37 CST 2021
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column t_user.password
	 *
	 * @param password the value for t_user.password
	 *
	 * @mbggenerated Tue Mar 16 04:16:37 CST 2021
	 */
	public void setPassword(String password) {
		this.password = password == null ? null : password.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column t_user.salt
	 *
	 * @return the value of t_user.salt
	 *
	 * @mbggenerated Tue Mar 16 04:16:37 CST 2021
	 */
	public String getSalt() {
		return salt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column t_user.salt
	 *
	 * @param salt the value for t_user.salt
	 *
	 * @mbggenerated Tue Mar 16 04:16:37 CST 2021
	 */
	public void setSalt(String salt) {
		this.salt = salt == null ? null : salt.trim();
	}

	@Override
	public String toString() {
		return "TUser [id=" + id + ", userNum=" + userNum + ", userName=" + userName + ", phone="
				+ phone + ", mailbox=" + mailbox + ", role=" + role + ", password=" + password
				+ ", salt=" + salt + "]";
	}

}