package com.computer.subscribe.pojo;

import javax.validation.constraints.Max;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Pattern;
import javax.validation.constraints.Size;

import org.hibernate.validator.constraints.Email;
import org.hibernate.validator.constraints.NotBlank;
import org.hibernate.validator.constraints.Range;

import io.swagger.annotations.ApiModelProperty;
import lombok.Data;

@Data
public class TUser {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column t_user.id
	 *
	 * @mbggenerated Thu Apr 08 23:43:19 CST 2021
	 */
	@ApiModelProperty(value = "ID")
	private Integer id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column t_user.user_num
	 *
	 * @mbggenerated Thu Apr 08 23:43:19 CST 2021
	 */
	@NotNull(message = "学号或工号不能为空")
	@Range(min = 1, max = 1000 * 1000 * 1000 * 1000)
	private Long userNum;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column t_user.user_name
	 *
	 * @mbggenerated Thu Apr 08 23:43:19 CST 2021
	 */
	@NotBlank(message = "用户名不能为空")
	@Size(max = 19)
	private String userName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column t_user.phone
	 *
	 * @mbggenerated Thu Apr 08 23:43:19 CST 2021
	 */
	@NotBlank(message = "电话不能为空")
	@Pattern(regexp = "^[1][3,4,5,6,7,8,9][0-9]{9}$", message = "电话格式有误")
	private String phone;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column t_user.mailbox
	 *
	 * @mbggenerated Thu Apr 08 23:43:19 CST 2021
	 */
	@NotBlank(message = "联系邮箱不能为空")
	@Email(message = "邮箱格式不对")
	@Size(min = 7, max = 79)
	private String mailbox;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column t_user.role
	 *
	 * @mbggenerated Thu Apr 08 23:43:19 CST 2021
	 */
	@NotNull(message = "帐户类型不能为空")
	@Max(value = 9)
	private Integer role;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column t_user.password
	 *
	 * @mbggenerated Thu Apr 08 23:43:19 CST 2021
	 */
	@Size(min = 3, max = 18)
	@NotBlank(message = "密码不能为空")
	private String password;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column t_user.salt
	 *
	 * @mbggenerated Thu Apr 08 23:43:19 CST 2021
	 */
	private String salt;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column t_user.id
	 *
	 * @return the value of t_user.id
	 *
	 * @mbggenerated Thu Apr 08 23:43:19 CST 2021
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column t_user.id
	 *
	 * @param id the value for t_user.id
	 *
	 * @mbggenerated Thu Apr 08 23:43:19 CST 2021
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column t_user.user_num
	 *
	 * @return the value of t_user.user_num
	 *
	 * @mbggenerated Thu Apr 08 23:43:19 CST 2021
	 */
	public Long getUserNum() {
		return userNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column t_user.user_num
	 *
	 * @param i the value for t_user.user_num
	 *
	 * @mbggenerated Thu Apr 08 23:43:19 CST 2021
	 */
	public void setUserNum(Long i) {
		this.userNum = i;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column t_user.user_name
	 *
	 * @return the value of t_user.user_name
	 *
	 * @mbggenerated Thu Apr 08 23:43:19 CST 2021
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column t_user.user_name
	 *
	 * @param userName the value for t_user.user_name
	 *
	 * @mbggenerated Thu Apr 08 23:43:19 CST 2021
	 */
	public void setUserName(String userName) {
		this.userName = userName == null ? null : userName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column t_user.phone
	 *
	 * @return the value of t_user.phone
	 *
	 * @mbggenerated Thu Apr 08 23:43:19 CST 2021
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column t_user.phone
	 *
	 * @param phone the value for t_user.phone
	 *
	 * @mbggenerated Thu Apr 08 23:43:19 CST 2021
	 */
	public void setPhone(String phone) {
		this.phone = phone == null ? null : phone.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column t_user.mailbox
	 *
	 * @return the value of t_user.mailbox
	 *
	 * @mbggenerated Thu Apr 08 23:43:19 CST 2021
	 */
	public String getMailbox() {
		return mailbox;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column t_user.mailbox
	 *
	 * @param mailbox the value for t_user.mailbox
	 *
	 * @mbggenerated Thu Apr 08 23:43:19 CST 2021
	 */
	public void setMailbox(String mailbox) {
		this.mailbox = mailbox == null ? null : mailbox.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column t_user.role
	 *
	 * @return the value of t_user.role
	 *
	 * @mbggenerated Thu Apr 08 23:43:19 CST 2021
	 */
	public Integer getRole() {
		return role;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column t_user.role
	 *
	 * @param role the value for t_user.role
	 *
	 * @mbggenerated Thu Apr 08 23:43:19 CST 2021
	 */
	public void setRole(Integer role) {
		this.role = role;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column t_user.password
	 *
	 * @return the value of t_user.password
	 *
	 * @mbggenerated Thu Apr 08 23:43:19 CST 2021
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column t_user.password
	 *
	 * @param password the value for t_user.password
	 *
	 * @mbggenerated Thu Apr 08 23:43:19 CST 2021
	 */
	public void setPassword(String password) {
		this.password = password == null ? null : password.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column t_user.salt
	 *
	 * @return the value of t_user.salt
	 *
	 * @mbggenerated Thu Apr 08 23:43:19 CST 2021
	 */
	public String getSalt() {
		return salt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column t_user.salt
	 *
	 * @param salt the value for t_user.salt
	 *
	 * @mbggenerated Thu Apr 08 23:43:19 CST 2021
	 */
	public void setSalt(String salt) {
		this.salt = salt == null ? null : salt.trim();
	}

	@Override
	public String toString() {
		return "TUser [id=" + id + ", userNum=" + userNum + ", userName=" + userName
				+ ", phone=" + phone + ", mailbox=" + mailbox + ", role=" + role
				+ ", password=" + password + ", salt=" + salt + "]";
	}

}