package com.computer.subscribe.mapper;

import com.computer.subscribe.pojo.TSubscribe;
import com.computer.subscribe.pojo.TSubscribeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TSubscribeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_subscribe
     *
     * @mbggenerated Sun Apr 11 11:21:42 CST 2021
     */
    int countByExample(TSubscribeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_subscribe
     *
     * @mbggenerated Sun Apr 11 11:21:42 CST 2021
     */
    int deleteByExample(TSubscribeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_subscribe
     *
     * @mbggenerated Sun Apr 11 11:21:42 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_subscribe
     *
     * @mbggenerated Sun Apr 11 11:21:42 CST 2021
     */
    int insert(TSubscribe record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_subscribe
     *
     * @mbggenerated Sun Apr 11 11:21:42 CST 2021
     */
    int insertSelective(TSubscribe record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_subscribe
     *
     * @mbggenerated Sun Apr 11 11:21:42 CST 2021
     */
    List<TSubscribe> selectByExample(TSubscribeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_subscribe
     *
     * @mbggenerated Sun Apr 11 11:21:42 CST 2021
     */
    TSubscribe selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_subscribe
     *
     * @mbggenerated Sun Apr 11 11:21:42 CST 2021
     */
    int updateByExampleSelective(@Param("record") TSubscribe record, @Param("example") TSubscribeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_subscribe
     *
     * @mbggenerated Sun Apr 11 11:21:42 CST 2021
     */
    int updateByExample(@Param("record") TSubscribe record, @Param("example") TSubscribeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_subscribe
     *
     * @mbggenerated Sun Apr 11 11:21:42 CST 2021
     */
    int updateByPrimaryKeySelective(TSubscribe record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_subscribe
     *
     * @mbggenerated Sun Apr 11 11:21:42 CST 2021
     */
    int updateByPrimaryKey(TSubscribe record);
}